version: '3.11'

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/personalised_nudges
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    ports:
      - 5432:5432  
    expose: 
      - 5432

volumes:
  postgres_data: